"""Re-check every reported finding against GitHub and refresh the derived counts.

The ethics section states how many maintainers were contacted and how many have
acted on the report. Those counts were tracked by hand once and went stale, which is
the failure mode this script removes: the status of each issue is read back from
GitHub, written into the tracker, and emitted as LaTeX macros the paper uses.

Two derived states, defined conservatively so the paper can state what it means:

  fixed     the reported issue is closed with state_reason "completed"
  released  fixed, and the repository published a release on or after the close date

Neither is proof that the defect is gone. The authoritative check is re-probing the
server with the harness, and the census re-run does that; these counts describe the
maintainer response, not the measured behavior.

Requires the `gh` CLI, authenticated. Reads and rewrites
data/disclosure_kit/CONTACTS.csv in place and writes paper/disclosure_numbers.tex.

Usage:
  python driver/check_disclosure_status.py [--offline]
"""

import argparse
import csv
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTACTS = ROOT / "data" / "disclosure_kit" / "CONTACTS.csv"
OUT_TEX = ROOT / "paper" / "disclosure_numbers.tex"

ISSUE_RE = re.compile(r"reported: (\S+?)#(\d+)")
COLUMNS = ["server", "identifier", "severity", "check", "repository", "notice_file",
           "status", "date_reported", "fix_state", "fix_checked"]


def api(path):
    p = subprocess.run(["gh", "api", path], capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if p.returncode != 0:
        return None
    try:
        return json.loads(p.stdout)
    except json.JSONDecodeError:
        return None


def issue_outcome(repo, num):
    """Return (fix_state, detail) for one reported issue."""
    iss = api(f"repos/{repo}/issues/{num}")
    if iss is None:
        return "unknown", "issue not readable"
    if iss["state"] != "closed":
        return "open", ""
    if iss.get("state_reason") != "completed":
        return "closed-other", iss.get("state_reason") or ""
    closed = iss.get("closed_at") or ""
    rel = api(f"repos/{repo}/releases?per_page=100") or []
    after = [r for r in rel
             if not r.get("draft") and (r.get("published_at") or "") >= closed]
    if after:
        newest = max(after, key=lambda r: r["published_at"])
        return "released", f"{newest.get('tag_name','?')} {newest['published_at'][:10]}"
    return "fixed", closed[:10]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--offline", action="store_true",
                    help="recompute the macros from the tracker without querying GitHub")
    args = ap.parse_args()

    with CONTACTS.open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    today = subprocess.run(["git", "log", "-1", "--format=%cs"], cwd=ROOT,
                           capture_output=True, text=True).stdout.strip()

    for r in rows:
        r.setdefault("fix_state", "")
        r.setdefault("fix_checked", "")
        m = ISSUE_RE.search(r.get("status") or "")
        if not m:
            continue
        if args.offline:
            continue
        state, detail = issue_outcome(m.group(1), m.group(2))
        r["fix_state"] = state
        r["fix_checked"] = today
        print(f"{m.group(1)}#{m.group(2)}\t{state}\t{detail}")

    with CONTACTS.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)

    md = [r for r in rows if r["check"] == "malformed-json"]
    reported = [r for r in md if ISSUE_RE.search(r.get("status") or "")]
    unreachable = [r for r in md if "unreachable" in (r.get("status") or "").lower()]
    fixed = [r for r in reported if r["fix_state"] in ("fixed", "released")]
    released = [r for r in reported if r["fix_state"] == "released"]
    silent = [r for r in rows if r["check"] == "tools-call-invalid-args"]

    macros = {
        "NMalformedDies": len(md),
        "NMalformedReported": len(reported),
        "NMalformedUnreachable": len(unreachable),
        "NMalformedFixed": len(fixed),
        "NMalformedReleased": len(released),
        "NSilentNotices": len(silent),
    }
    bs = chr(92)  # a lone backslash, kept out of the f-strings
    body = ["% Generated by driver/check_disclosure_status.py -- do not hand-edit.",
            "% Maintainer response to the disclosure log, read back from GitHub.",
            f"% Last checked: {today}"]
    body += [bs + "newcommand{" + bs + k + "}{" + str(v) + "}"
             for k, v in macros.items()]
    OUT_TEX.write_text("\n".join(body) + "\n", encoding="utf-8")

    print(f"\nwrote {OUT_TEX.relative_to(ROOT)}")
    for k, v in macros.items():
        print(f"  {k:24} {v}")


if __name__ == "__main__":
    main()
