"""Generate paper/numbers.tex from the final dataset.

Every number cited in the paper comes from here, so prose can never drift from
data. Run after the final clean dataset is complete.

Usage:
  python make_numbers.py [--in data/probe_results.jsonl] [--out paper/numbers.tex]
"""

import argparse
import json
import math
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"


def wilson(k: int, n: int):
    """95% Wilson score interval for a proportion (robust for small/edge counts)."""
    if n == 0:
        return (0.0, 0.0, 0.0)
    z = 1.96
    p = k / n
    denom = 1 + z * z / n
    center = (p + z * z / (2 * n)) / denom
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / denom
    return (p, max(0.0, center - half), min(1.0, center + half))


def pctci(k, n):
    p, lo, hi = wilson(k, n)
    return f"{100*p:.1f}\\% (95\\% CI {100*lo:.1f}--{100*hi:.1f})"


def load(path):
    by = {}
    with path.open(encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            by[r.get("server_name") or json.dumps(r.get("cmd"))] = r
    return list(by.values())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", default=str(DATA / "probe_results.jsonl"))
    ap.add_argument("--out", default=str(ROOT / "paper" / "numbers.tex"))
    ap.add_argument("--frame", default=str(DATA / "frame_latest.jsonl"))
    args = ap.parse_args()

    rows = load(Path(args.inp))
    n = len(rows)
    hs = sum(1 for r in rows if r.get("handshake_ok"))
    responders = [r for r in rows if r.get("handshake_ok")]
    n_resp = len(responders)

    def resp_rate(pred):
        k = sum(1 for r in responders for c in r.get("checks", []) if pred(c))
        return k, pctci(k, n_resp)

    err_as_result_k, err_as_result = resp_rate(
        lambda c: c["id"] == "tools-call-unknown" and c["verdict"] == "error-as-result")
    notypecheck_k, notypecheck = resp_rate(
        lambda c: c["id"] == "tools-call-invalid-args" and c["verdict"] == "fail")
    malformed_k, malformed = resp_rate(
        lambda c: c["id"] == "malformed-json" and c["verdict"] == "fail")

    frame_n = sum(1 for _ in open(args.frame, encoding="utf-8"))

    macros = {
        "Nframe": f"{frame_n:,}",
        "Nprobed": f"{n:,}",
        "Nresponders": f"{n_resp:,}",
        "HandshakeRate": pctci(hs, n),
        "HandshakeCount": str(hs),
        "ErrAsResultRate": err_as_result,
        "ErrAsResultCount": str(err_as_result_k),
        "NoTypecheckRate": notypecheck,
        "MalformedDiesRate": malformed,
    }
    lines = ["% AUTO-GENERATED by driver/make_numbers.py -- do not edit by hand."]
    lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in macros.items()]
    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.out} ({n} servers, {n_resp} responders)")
    for k, v in macros.items():
        print(f"  \\{k} = {v}")


if __name__ == "__main__":
    main()
