"""Emit paper/validation_numbers.tex from the blinded rating pass.

The census classifier sorts responses to a poisoned argument into
silent-execution and in-band-error. A human rater labeled a stratified sample
blind, with the classifier's answer hidden. This script turns that sample into
the macros the paper cites: agreement, precision, recall, and a corrected count
that reweights each stratum by its size in the census.

    python validation/make_validation_numbers.py

Inputs live under private/ because they carry server identities. The labels
themselves are released with identities removed by make_release.py.
"""

import csv
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "driver"))
from stats import wilson  # noqa: E402

RATING = ROOT / "private" / "rating"
OUT = ROOT / "paper" / "validation_numbers.tex"


def kappa(pairs):
    n = len(pairs)
    po = sum(a == b for a, b in pairs) / n
    ca, cb = Counter(a for a, _ in pairs), Counter(b for _, b in pairs)
    pe = sum(ca[k] * cb[k] for k in set(ca) | set(cb)) / n ** 2
    return (po - pe) / (1 - pe)


def main():
    key = json.loads((RATING / "key.json").read_text(encoding="utf-8"))
    with (RATING / "human.csv").open(encoding="utf-8-sig", newline="") as f:
        human = {r["item_id"]: r["label"].strip()
                 for r in csv.DictReader(f) if r.get("label", "").strip()}
    cons = json.loads((ROOT / "data" / "consequences.json").read_text(encoding="utf-8"))

    n_sil, n_inb = len(cons["silent-execution"]), len(cons["in-band-error"])
    pairs, tp, fp, fn, tn = [], 0, 0, 0, 0
    sil, inb = [], []
    for iid, label in human.items():
        pred = key[iid]["bucket"] == "silent-execution"
        act = label == "EXECUTED"
        pairs.append(("EXEC" if pred else "NOT", "EXEC" if act else "NOT"))
        tp += pred and act
        fp += pred and not act
        fn += (not pred) and act
        tn += (not pred) and not act
        (sil if pred else inb).append(act)

    k = kappa(pairs)
    agree = sum(1 for a, b in pairs if a == b)
    p_sil, lo_s, hi_s = wilson(sum(sil), len(sil))
    p_inb, lo_i, hi_i = wilson(sum(inb), len(inb))
    est = n_sil * p_sil + n_inb * p_inb

    macros = {
        "ValN": f"{len(human)}",
        "ValAgree": f"{agree}",
        "ValKappa": f"{k:.2f}",
        "ValPrecision": f"{100*tp/(tp+fp):.0f}\\%" if tp + fp else "-",
        "ValRecall": f"{100*tp/(tp+fn):.0f}\\%" if tp + fn else "-",
        "ValSilN": f"{len(sil)}",
        "ValInbN": f"{len(inb)}",
        "ValSilExecPct": f"{100*p_sil:.0f}\\%",
        "ValInbExecPct": f"{100*p_inb:.0f}\\%",
        "NSilentExecCorrected": f"{est:.0f}",
        "NSilentExecCorrectedLo": f"{n_sil*lo_s + n_inb*lo_i:.0f}",
        "NSilentExecCorrectedHi": f"{n_sil*hi_s + n_inb*hi_i:.0f}",
    }
    lines = ["% AUTO-GENERATED by validation/make_validation_numbers.py."]
    lines += [f"\\newcommand{{\\{k2}}}{{{v}}}" for k2, v in macros.items()]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    for k2, v in macros.items():
        print(f"  \\{k2} = {v}")


if __name__ == "__main__":
    main()
